POST http://localhost:8080/api/v1/citizen
Content-Type: application/json

{

  "firstName": "Deepen Gautam ",
  "middleName": " ",
  "lastName": "Ju",
  "gender": "MALE",
  "spouseName": "Hen Tin",
  "nationality": "Nepali",
  "district": "Kathmandu",
  "municipality": "Tokha",
  "wardNo": 3,
  "tole": "Dhapasi",
  "fatherName": "Sitaram Katwal",
  "motherName": "Nar Kumari Katwal",
  "grandfatherName": "Bhupadhoj Katwal",
  "grandmotherName": "Radha Thapa",
  "dateOfBirth": "2001-02-26",
  "phoneNo": "9147741001433"

}
