POST http://localhost:8080/api/v1/staff/super-admin
Content-Type: application/json

{
  "fullName": "Super Admin",
  "email": "superpara@gmail.com",
  "password": "kk",
  "phoneNumber": "98000000000",
  "designation": "Chief Administrator",
  "department": "ADMINISTRATION_DEPARTMENT",
  "addedBy": "Kalyan Katwal",
  "role": "SUPERADMIN",
  "district": "Bara",
  "municipality": "Para"
}
