POST http://localhost:8080/api/v1/citizen
Content-Type: application/json

{

  "firstName": "Manush",
  "middleName": "Bahadur",
  "lastName": "Thapa",
  "gender": "MALE",
  "spouseName": "Manju Nepali",
  "nationality": "Nepali",
  "district": "Kathmandu",
  "municipality": "Tokha",
  "wardNo": 3,
  "tole": "Dhapasi",
  "fatherName": "Hari Bahadur Thapa",
  "motherName": "Gita Thapa",
  "grandfatherName": "Madhan Thapa",
  "grandmotherName": "Radha Thapa",
  "dateOfBirth": "2020-02-05",
  "phoneNo": "911011232333"
}
