POST http://localhost:8080/api/v1/whatsapp/otp/send
Content-Type: application/json

{
  "messaging_product": "whatsapp",
  "to": "+9779817785867",
  "type": "template",
  "template": {
    "name": "otp_template",
    "language": {
      "code": "en_US"
    },
    "components": [
      {
        "type": "body",
        "parameters": [
          {
            "type": "text",
            "text": "123456"
          }
        ]
      }
    ]
  }
}




